--part_A
--1
SELECT * FROM DEPOSITE
--2
SELECT * FROM BORROW
--3
SELECT  * FROM CUSTOMER
--4
SELECT ACTNO NO,CNAME,AMOUNT FROM DEPOSITE
--5
SELECT LOANNO FROM BORROW
--6
SELECT*FROM BORROW WHERE BNAME='ANDHERI'
--7 
SELECT AMOUNT FROM DEPOSITE WHERE ACTNO=106
--8
SELECT CNAME FROM BORROW WHERE AMOUNT>5000
--9
SELECT CNAME FROM DEPOSITE WHERE ADATE>95-12-1
--10
SELECT CNAME FROM DEPOSITE WHERE ACTNO<105
--11
SELECT CNAME FROM CUSTOMER WHERE CITY IN('NAGPUR','DELHI')
SELECT CNAME FROM CUSTOMER WHERE CITY='NAGPUR' OR CITY='DELHI'
--12
SELECT CNAME FROM DEPOSITE WHERE AMOUNT>4000 AND ACTNO<105
--13
SELECT CNAME FROM BORROW WHERE AMOUNT>=3000 AND AMOUNT<=8000
SELECT CNAME FROM BORROW WHERE AMOUNT BETWEEN 3000 AND 8000
--14
SELECT * FROM DEPOSITE WHERE BNAME<>'ANDHERI'
--15
SELECT ACTNO,CNAME,BNAME FROM DEPOSITE WHERE BNAME IN('AJNI','KAROLBAGH','M.G.ROAD') 

--part_B

SELECT*,AMOUNT *1.1 AS EXTRA_AMOUNT FROM BORROW

SELECT *FROM BORROW WHERE LOANNO%2=1